version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/FH_frontend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "gradle"
    directory: "/FH_backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
